from package.ezorm.variables import EzORM
from pydantic import Field
from typing import Optional

class DPoPModel(EzORM):
    jti:str = Field(description="your unique jti", default=None)

class AccessTokenModel(DPoPModel):
    access_token:str = Field(description="access token generated by server", default=None)
    client_id:str = Field(description="client it retrieved from client", default=None)
    exp:int = Field(description="expiration on access token should be less than an hour", default=None)
    active:bool = Field(description="true if a record is still valid, otherwise false", default=None)
    remark:Optional[str] = Field(description="reason why each record changes active from true to false", default=None)

class RefreshTokenModel(AccessTokenModel):
    refresh_token:str = Field(description="expiration varied from token type", default=None)
    exp:int = Field(description="expiration on access token should be at least a day", default=None)